### ISSUE TITLE
Add tests for the scene format plugin

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#157]
**Describe the feature you'd like**
Add tests for the new feature in #151 

**Additional context**
We should do this after #124 , since adding new tests (a new type of tests) will be easier after making more progress with the cmake conversion and the best ways to test this feature is compare generated output from custom commands, which is not trivial with the current test suite.

Tests to add:
- [ ] Option node translation #321 
- [ ] Motion key support #348
- [ ] Per channel connections #352
- [ ] Writing polymesh.subdiv_iterations #353
- [ ] Writing ginstance attributes #363
- [ ] Textured mesh light support #366
- [ ] Writing motion range #369
- [ ] Writing toon shader #377
- [ ] Linking to array attribute elements #381
- [ ] UsdGeomCamera support #388
- [ ] Load namespaced primvars #383
- [ ] Write connections for user-data of type NODE #371 
- [ ] Support motion blur in the scene format loader #347
